version: '3.8'

services:
  postgres:
    image: postgres:17.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # Монтируем каталог с SQL-скриптами

  app:
    build: ./app
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  tester:
    build: ./tester
    environment:
      API_URL: http://nginx
    depends_on:
      - nginx

volumes:
  postgres_data:


# docker-compose up --build

# docker-compose run tester npm test